"""Schema re-exports."""

from src.schemas.rbac import (
    ChangePasswordSchema,
    DeptBase,
    DeptCreate,
    DeptOut,
    DeptUpdate,
    LoginSchema,
    MenuBase,
    MenuCreate,
    MenuOut,
    MenuUpdate,
    RoleBase,
    RoleCreate,
    RoleOut,
    RoleUpdate,
    TokenSchema,
    UserBase,
    UserCreate,
    UserOut,
    UserUpdate,
)
from src.schemas.ai import (
    ProviderBase,
    ProviderCreate,
    ProviderUpdate,
    ProviderOut,
    ChatMessage,
    ChatRequest,
    ChatStreamRequest,
)
from src.schemas.plugin import PluginOut, PluginToggle, PluginConfigUpdate
from src.schemas.log import LogOut
from src.schemas.setting import SettingOut, SettingUpdate, SettingsBatchUpdate, PublicSettingsOut

__all__ = [
    "LoginSchema",
    "TokenSchema",
    "ChangePasswordSchema",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserOut",
    "RoleBase",
    "RoleCreate",
    "RoleUpdate",
    "RoleOut",
    "MenuBase",
    "MenuCreate",
    "MenuUpdate",
    "MenuOut",
    "DeptBase",
    "DeptCreate",
    "DeptUpdate",
    "DeptOut",
    "ProviderBase",
    "ProviderCreate",
    "ProviderUpdate",
    "ProviderOut",
    "ChatMessage",
    "ChatRequest",
    "ChatStreamRequest",
    "PluginOut",
    "PluginToggle",
    "PluginConfigUpdate",
    "LogOut",
    "SettingOut",
    "SettingUpdate",
    "SettingsBatchUpdate",
    "PublicSettingsOut",
]
