"""Installation wizard state management.

The wizard runs when the backend starts WITHOUT a valid database config:
  - `.env` missing / DB_* empty, or
  - a marker file `setup.lock` (written after successful install) is absent.

Design:
  - All wizard state lives in `src/setup_wizard` (outside app DB access).
  - On install: write `.env` from user input, create DB, seed, then tell the
    user to restart. A `setup.lock` marker prevents re-running the wizard.
  - The running process keeps serving `/setup` until restart.
"""

from __future__ import annotations

import json
from pathlib import Path

from src.core.config import settings

BACKEND_DIR = Path(__file__).resolve().parent.parent.parent  # src/setup_wizard → src → backend
ENV_FILE = BACKEND_DIR / ".env"
LOCK_FILE = BACKEND_DIR / "setup.lock"


def is_installed() -> bool:
    """True when the installation wizard has been completed (lock exists)."""
    return LOCK_FILE.exists()


def setup_status() -> dict:
    """Current wizard status for the frontend."""
    return {
        "installed": is_installed(),
        "env_exists": ENV_FILE.exists(),
        "db_configured": _db_configured(),
        "setup_url": "/setup",
    }


def _db_configured() -> bool:
    """Whether a MySQL or SQLite database is usable in the current config."""
    if settings.DB_TYPE == "mysql":
        return bool(settings.DB_NAME and settings.DB_USER)
    return bool(settings.DB_NAME)


def write_env(
    *,
    db_type: str,
    db_host: str,
    db_port: int,
    db_user: str,
    db_password: str,
    db_name: str,
    jwt_secret: str,
    admin_username: str,
    admin_password: str,
    cors_origins: list[str],
    site_name: str = "ApeAdmin",
    admin_path: str = "/admin",
    site_url: str = "",
) -> None:
    """Write the production .env from wizard input (overwrites existing)."""
    cors = json.dumps(cors_origins, ensure_ascii=False)
    lines = [
        "# Generated by ApeAdmin setup wizard",
        f"APP_NAME={site_name}",
        "DEBUG=False",
        "",
        "# ---- Database ----",
        f"DB_TYPE={db_type}",
        f"DB_HOST={db_host}",
        f"DB_PORT={db_port}",
        f"DB_USER={db_user}",
        f"DB_PASSWORD={db_password}",
        f"DB_NAME={db_name}",
        "",
        "# ---- Security ----",
        f"JWT_SECRET={jwt_secret}",
        "",
        "# ---- Super admin (first-boot seed) ----",
        f"SUPER_ADMIN_USERNAME={admin_username}",
        f"SUPER_ADMIN_PASSWORD={admin_password}",
        "",
        "# ---- Site ----",
        f"ADMIN_PATH={admin_path}",
        f"SITE_URL={site_url}",
        "",
        "# ---- CORS ----",
        f"CORS_ORIGINS={cors}",
        "",
        "# ---- Features ----",
        "MCP_ENABLED=True",
        "PLUGINS_ENABLED=True",
    ]
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_lock(result: dict) -> None:
    """Persist install result (for the success page after restart)."""
    LOCK_FILE.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
