"""AegisCode 项目模板 — 新建项目时自动生成初始文件。

支持模板:
  - python:  Python 项目 (FastAPI 风格)
  - node:    Node.js 项目 (Express 风格)
  - web:     前端项目 (HTML+CSS+JS)
  - empty:   空项目 (仅默认目录)
"""

from __future__ import annotations

from pathlib import Path

# ── 模板定义 ──────────────────────────────────────────────────────────

TEMPLATES: dict[str, dict] = {
    "python": {
        "label": "Python 项目",
        "description": "FastAPI 风格 Python 项目，含 main.py 和 requirements.txt",
        "files": {
            "main.py": '''"""AegisCode 自动生成的 Python 项目入口。"""
from fastapi import FastAPI

app = FastAPI(title="My API", version="0.1.0")


@app.get("/")
async def root():
    return {"message": "Hello from AegisCode!"}


@app.get("/health")
async def health():
    return {"status": "ok"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
''',
            "requirements.txt": "fastapi\nuvicorn\n",
            "README.md": "# Python Project\n\nGenerated by AegisCode.\n",
        },
    },
    "node": {
        "label": "Node.js 项目",
        "description": "Express 风格 Node.js 项目，含 index.js 和 package.json",
        "files": {
            "index.js": '''// AegisCode 自动生成的 Node.js 项目入口
const express = require('express')

const app = express()
const PORT = process.env.PORT || 3000

app.get('/', (req, res) => {
  res.json({ message: 'Hello from AegisCode!' })
})

app.get('/health', (req, res) => {
  res.json({ status: 'ok' })
})

app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`)
})
''',
            "package.json": '''{
  "name": "my-node-app",
  "version": "0.1.0",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "dev": "node --watch index.js"
  },
  "dependencies": {
    "express": "^4.18.0"
  }
}
''',
            "README.md": "# Node.js Project\n\nGenerated by AegisCode.\n",
        },
    },
    "web": {
        "label": "前端项目",
        "description": "HTML + CSS + JavaScript 前端项目",
        "files": {
            "index.html": '''<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Web App</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div id="app">
    <h1>Hello from AegisCode!</h1>
    <p>Generated web project.</p>
  </div>
  <script src="script.js"></script>
</body>
</html>
''',
            "style.css": '''* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: system-ui, -apple-system, sans-serif; padding: 2rem; color: #1f2937; }
h1 { color: #4f46e5; margin-bottom: 0.5rem; }
''',
            "script.js": '''// AegisCode 自动生成
console.log("Hello from AegisCode!");
''',
            "README.md": "# Web Project\n\nGenerated by AegisCode.\n",
        },
    },
    "empty": {
        "label": "空项目",
        "description": "不含任何初始文件，仅有默认目录结构",
        "files": {},
    },
}


def apply_template(project_path: Path, template: str | None) -> None:
    """在项目目录下按模板创建初始文件。

    Args:
        project_path: 已存在的项目根目录
        template: 模板名 (python/node/web/empty)，None 或未知模板则跳过
    """
    if not template or template not in TEMPLATES:
        return

    tpl = TEMPLATES[template]
    for rel_path, content in tpl.get("files", {}).items():
        full_path = project_path / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        if not full_path.exists():
            full_path.write_text(content, encoding="utf-8")


def list_templates() -> list[dict]:
    """返回可用模板列表（供前端展示）。"""
    return [
        {"key": key, "label": tpl["label"], "description": tpl["description"]}
        for key, tpl in TEMPLATES.items()
    ]
